<#
@Author: [FD] Pelessaria, Codex / Cursor AI for Bugfixing

I3D Mapping Exporter - XML Updater
Purpose:
  Updates the i3dMappings section in an existing vehicle/placeable XML.

How it works:
  - The GE Lua script copies generated mappings to the Windows clipboard.
  - The BAT file starts this script and passes the target XML using -TargetXml and the UI language using -Language.
  - Existing mapping IDs get their node path updated; missing IDs are added.
  - Mapping entries are normalized to node="0>..." />. Other mapping IDs remain.

Formatting and file handling:
  - Edits the XML text directly instead of serializing the whole document.
  - Keeps unrelated text, blank lines, indentation, line endings, and file encoding.
  - Writes through a temporary file before replacing the target XML.

Requirements:
  - Windows PowerShell with Get-Clipboard and Windows Forms available.
  - Clipboard text must contain mapping elements generated by the GE Lua script.
  - The target XML must already contain an i3dMappings section.

The script displays a message box with the update result or any error.

█████     ███     ████     █   █    ███    █   █     ███        ████     █   █    ████      ████       
█        █   █    █   █    ██ ██     █     ██  █    █           █   █    █   █    █   █    █           
████     █████    ████     █ █ █     █     █ █ █    █  ██       █   █    █   █    █   █     ███        
█        █   █    █  █     █   █     █     █  ██    █   █       █   █    █   █    █   █        █       
█        █   █    █   █    █   █    ███    █   █     ███        ████      ███     ████     ████        
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$TargetXml,
    [ValidateSet('de', 'en')]
    [string]$Language = 'de'
)

$ErrorActionPreference = 'Stop'
function Get-LocalizedText {
    param(
        [string]$German,
        [string]$English
    )

    if ($Language -eq 'en') {
        return $English
    }
    return $German
}

function Show-Result {
    param(
        [string]$Message,
        [bool]$IsError = $false
    )

    Add-Type -AssemblyName System.Windows.Forms
    $icon = [System.Windows.Forms.MessageBoxIcon]::Information
    if ($IsError) {
        $icon = [System.Windows.Forms.MessageBoxIcon]::Error
    }

    [void][System.Windows.Forms.MessageBox]::Show(
        $Message,
        'I3D Mapping Exporter',
        [System.Windows.Forms.MessageBoxButtons]::OK,
        $icon
    )
}

function Get-XmlTags {
    param(
        [string]$Text,
        [int]$Start,
        [int]$Length
    )

    $tags = New-Object 'System.Collections.Generic.List[object]'
    $rangeEnd = [Math]::Min($Text.Length, $Start + $Length)
    $position = $Start

    while ($position -lt $rangeEnd) {
        $left = $Text.IndexOf('<', $position)
        if ($left -lt 0 -or $left -ge $rangeEnd) {
            break
        }

        $tail = $Text.Substring($left)
        if ($tail.StartsWith('<!--', [System.StringComparison]::Ordinal)) {
            $commentEnd = $Text.IndexOf('-->', $left + 4, [System.StringComparison]::Ordinal)
            if ($commentEnd -lt 0) {
                break
            }
            $position = $commentEnd + 3
            continue
        }
        if ($tail.StartsWith('<![CDATA[', [System.StringComparison]::Ordinal)) {
            $cdataEnd = $Text.IndexOf(']]>', $left + 9, [System.StringComparison]::Ordinal)
            if ($cdataEnd -lt 0) {
                break
            }
            $position = $cdataEnd + 3
            continue
        }
        if ($tail.StartsWith('<?', [System.StringComparison]::Ordinal)) {
            $piEnd = $Text.IndexOf('?>', $left + 2, [System.StringComparison]::Ordinal)
            if ($piEnd -lt 0) {
                break
            }
            $position = $piEnd + 2
            continue
        }

        $isDeclaration = $tail.StartsWith('<!', [System.StringComparison]::Ordinal)
        $quote = [char]0
        $bracketDepth = 0
        $tagEnd = -1
        for ($index = $left + 1; $index -lt $rangeEnd; $index++) {
            $character = $Text[$index]
            if ($quote -ne [char]0) {
                if ($character -eq $quote) {
                    $quote = [char]0
                }
                continue
            }

            if ($character -eq '"' -or $character -eq [char]39) {
                $quote = $character
            } elseif ($isDeclaration -and $character -eq '[') {
                $bracketDepth++
            } elseif ($isDeclaration -and $character -eq ']' -and $bracketDepth -gt 0) {
                $bracketDepth--
            } elseif ($character -eq '>' -and $bracketDepth -eq 0) {
                $tagEnd = $index
                break
            }
        }

        if ($tagEnd -lt 0) {
            break
        }

        if (-not $isDeclaration) {
            $inside = $Text.Substring($left + 1, $tagEnd - $left - 1)
            $nameMatch = [regex]::Match(
                $inside,
                '^\s*(?<closing>/)?\s*(?<name>[A-Za-z_][A-Za-z0-9_.:-]*)'
            )
            if ($nameMatch.Success) {
                $isClosing = $nameMatch.Groups['closing'].Success
                $tagText = $Text.Substring($left, $tagEnd - $left + 1)
                $isSelfClosing = -not $isClosing -and $tagText.Substring(0, $tagText.Length - 1).TrimEnd().EndsWith('/')
                [void]$tags.Add([PSCustomObject]@{
                    Start = $left
                    End = $tagEnd + 1
                    Name = $nameMatch.Groups['name'].Value
                    Closing = $isClosing
                    SelfClosing = $isSelfClosing
                })
            }
        }

        $position = $tagEnd + 1
    }

    return $tags.ToArray()
}

function Get-MappingSection {
    param([string]$Text)

    $tags = @(Get-XmlTags -Text $Text -Start 0 -Length $Text.Length)
    for ($openIndex = 0; $openIndex -lt $tags.Count; $openIndex++) {
        $openTag = $tags[$openIndex]
        if ($openTag.Name -cne 'i3dMappings' -or $openTag.Closing) {
            continue
        }

        if ($openTag.SelfClosing) {
            return [PSCustomObject]@{
                Start = $openTag.Start
                OpenEnd = $openTag.End
                ContentStart = $openTag.End
                CloseStart = $openTag.End
                End = $openTag.End
                SelfClosing = $true
            }
        }

        $depth = 1
        for ($index = $openIndex + 1; $index -lt $tags.Count; $index++) {
            $tag = $tags[$index]
            if ($tag.Name -cne 'i3dMappings') {
                continue
            }

            if ($tag.Closing) {
                $depth--
                if ($depth -eq 0) {
                    return [PSCustomObject]@{
                        Start = $openTag.Start
                        OpenEnd = $openTag.End
                        ContentStart = $openTag.End
                        CloseStart = $tag.Start
                        End = $tag.End
                        SelfClosing = $false
                    }
                }
            } elseif (-not $tag.SelfClosing) {
                $depth++
            }
        }

        throw (Get-LocalizedText -German 'Die i3dMappings-Sektion besitzt kein schliessendes Tag.' -English 'The i3dMappings section has no closing tag.')
    }

    throw (Get-LocalizedText -German 'Keine i3dMappings-Sektion in der Ziel-XML gefunden.' -English 'No i3dMappings section was found in the target XML.')
}

function Get-AttributeValue {
    param(
        [string]$TagText,
        [string]$Name
    )

    $pattern = '(?<![A-Za-z0-9_.:-])' + [regex]::Escape($Name) + '\s*=\s*(?:"(?<double>[\s\S]*?)"|''(?<single>[\s\S]*?)'')'
    $match = [regex]::Match($TagText, $pattern)
    if (-not $match.Success) {
        return $null
    }

    $value = $match.Groups['double'].Value
    if ($match.Groups['single'].Success) {
        $value = $match.Groups['single'].Value
    }
    return [System.Net.WebUtility]::HtmlDecode($value)
}

function Escape-XmlAttribute {
    param([string]$Value)

    return $Value.Replace('&', '&amp;').Replace('<', '&lt;').Replace('"', '&quot;')
}

function Set-NodeAttribute {
    param(
        [string]$TagText,
        [string]$NodeValue
    )

    $pattern = '(?<![A-Za-z0-9_.:-])(?<before>node\s*=\s*)(?:"(?<double>[\s\S]*?)"|''(?<single>[\s\S]*?)'')'
    $match = [regex]::Match($TagText, $pattern)
    if ($match.Success) {
        $quote = '"'
        if ($match.Groups['single'].Success) {
            $quote = [string][char]39
        }
        $escapedValue = Escape-XmlAttribute -Value $NodeValue
        $replacement = $match.Groups['before'].Value + $quote + $escapedValue + $quote
        $updatedTag = $TagText.Remove($match.Index, $match.Length).Insert($match.Index, $replacement)
    } else {
        $escapedValue = Escape-XmlAttribute -Value $NodeValue
        $beforeEnd = $TagText.Substring(0, $TagText.Length - 1)
        $trimmed = $beforeEnd.TrimEnd()
        if ($trimmed.EndsWith('/')) {
            $insertAt = $beforeEnd.LastIndexOf('/')
        } else {
            $insertAt = $beforeEnd.Length
        }
        $updatedTag = $TagText.Insert($insertAt, ' node="' + $escapedValue + '"')
    }

    # Einheitliche GIANTS-Formatierung fuer leere Mapping-Tags.
    return [regex]::Replace($updatedTag, '\s*/\s*>$', ' />')
}
function Get-FileEncodingInfo {
    param([byte[]]$Bytes)

    $bomLength = 0
    $encoding = $null

    if ($Bytes.Length -ge 4 -and $Bytes[0] -eq 0x00 -and $Bytes[1] -eq 0x00 -and $Bytes[2] -eq 0xFE -and $Bytes[3] -eq 0xFF) {
        $bomLength = 4
        $encoding = [System.Text.UTF32Encoding]::new($true, $false)
    } elseif ($Bytes.Length -ge 4 -and $Bytes[0] -eq 0xFF -and $Bytes[1] -eq 0xFE -and $Bytes[2] -eq 0x00 -and $Bytes[3] -eq 0x00) {
        $bomLength = 4
        $encoding = [System.Text.UTF32Encoding]::new($false, $false)
    } elseif ($Bytes.Length -ge 3 -and $Bytes[0] -eq 0xEF -and $Bytes[1] -eq 0xBB -and $Bytes[2] -eq 0xBF) {
        $bomLength = 3
        $encoding = [System.Text.UTF8Encoding]::new($false, $true)
    } elseif ($Bytes.Length -ge 2 -and $Bytes[0] -eq 0xFE -and $Bytes[1] -eq 0xFF) {
        $bomLength = 2
        $encoding = [System.Text.UnicodeEncoding]::new($true, $false)
    } elseif ($Bytes.Length -ge 2 -and $Bytes[0] -eq 0xFF -and $Bytes[1] -eq 0xFE) {
        $bomLength = 2
        $encoding = [System.Text.UnicodeEncoding]::new($false, $false)
    } else {
        $headerLength = [Math]::Min($Bytes.Length, 512)
        $header = [System.Text.Encoding]::ASCII.GetString($Bytes, 0, $headerLength)
        $declaration = [regex]::Match($header, '<\?xml[^>]*encoding\s*=\s*["''](?<name>[^"'']+)["'']')
        if ($declaration.Success) {
            $encoding = [System.Text.Encoding]::GetEncoding(
                $declaration.Groups['name'].Value,
                [System.Text.EncoderFallback]::ExceptionFallback,
                [System.Text.DecoderFallback]::ExceptionFallback
            )
        } else {
            $encoding = [System.Text.UTF8Encoding]::new($false, $true)
        }
    }

    return [PSCustomObject]@{
        Encoding = $encoding
        BomLength = $bomLength
    }
}

function Get-LineStart {
    param(
        [string]$Text,
        [int]$Position
    )

    if ($Position -le 0) {
        return 0
    }

    $newlinePosition = $Text.LastIndexOf([char]10, $Position - 1)
    return $newlinePosition + 1
}

try {
    if (-not (Test-Path -LiteralPath $TargetXml -PathType Leaf)) {
        throw ((Get-LocalizedText -German 'Ziel-XML nicht gefunden: {0}' -English 'Target XML not found: {0}') -f $TargetXml)
    }

    $clipboardText = Get-Clipboard -Raw
    if ([string]::IsNullOrWhiteSpace($clipboardText)) {
        throw (Get-LocalizedText -German 'Die Zwischenablage enthaelt keine Mappings.' -English 'The clipboard does not contain any mappings.')
    }
    $clipboardText = $clipboardText.TrimEnd([char]0).Trim()
    if ($clipboardText -match '^\s*<i3dMappings(?:\s|>)') {
        $mappingXml = $clipboardText
    } else {
        $mappingXml = '<i3dMappings>' + $clipboardText + '</i3dMappings>'
    }

    $mappingDocument = New-Object System.Xml.XmlDocument
    $mappingDocument.XmlResolver = $null
    $mappingDocument.PreserveWhitespace = $true
    $mappingDocument.LoadXml($mappingXml)

    $incoming = [System.Collections.Generic.Dictionary[string,string]]::new([System.StringComparer]::Ordinal)
    foreach ($mappingNode in $mappingDocument.DocumentElement.SelectNodes('./i3dMapping')) {
        $mappingId = $mappingNode.GetAttribute('id')
        $nodePath = $mappingNode.GetAttribute('node')
        if ([string]::IsNullOrWhiteSpace($mappingId) -or [string]::IsNullOrWhiteSpace($nodePath)) {
            continue
        }
        $incoming[$mappingId] = $nodePath
    }
    if ($incoming.Count -eq 0) {
        throw (Get-LocalizedText -German 'In der Zwischenablage wurden keine gueltigen i3dMapping-Eintraege gefunden.' -English 'No valid i3dMapping entries were found in the clipboard.')
    }

    $resolvedTarget = (Resolve-Path -LiteralPath $TargetXml).Path
    $sourceBytes = [System.IO.File]::ReadAllBytes($resolvedTarget)
    $encodingInfo = Get-FileEncodingInfo -Bytes $sourceBytes
    $encoding = $encodingInfo.Encoding
    $bomLength = $encodingInfo.BomLength
    $xmlText = $encoding.GetString($sourceBytes, $bomLength, $sourceBytes.Length - $bomLength)

    $section = Get-MappingSection -Text $xmlText
    $newline = [string][char]13 + [char]10
    if (-not $xmlText.Contains($newline)) {
        if ($xmlText.Contains([string][char]10)) {
            $newline = [string][char]10
        } elseif ($xmlText.Contains([string][char]13)) {
            $newline = [string][char]13
        }
    }

    $existingTags = @()
    if (-not $section.SelfClosing) {
        $bodyLength = $section.CloseStart - $section.ContentStart
        $existingTags = @(Get-XmlTags -Text $xmlText -Start $section.ContentStart -Length $bodyLength |
            Where-Object { $_.Name -ceq 'i3dMapping' -and -not $_.Closing })
    }

    $existingIds = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    $matchedIds = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    $replacements = New-Object 'System.Collections.Generic.List[object]'
    foreach ($tag in $existingTags) {
        $rawTag = $xmlText.Substring($tag.Start, $tag.End - $tag.Start)
        $existingId = Get-AttributeValue -TagText $rawTag -Name 'id'
        if ([string]::IsNullOrEmpty($existingId)) {
            continue
        }
        [void]$existingIds.Add($existingId)

        if ($incoming.ContainsKey($existingId)) {
            $newTag = Set-NodeAttribute -TagText $rawTag -NodeValue $incoming[$existingId]
            [void]$matchedIds.Add($existingId)
        } else {
            $currentNode = Get-AttributeValue -TagText $rawTag -Name 'node'
            if ($null -ne $currentNode) {
                # Auch bestehende &gt;-Pfade auf die gewuenschte rohe 0>-Form normalisieren.
                $newTag = Set-NodeAttribute -TagText $rawTag -NodeValue $currentNode
            } else {
                $newTag = [regex]::Replace($rawTag, '\s*/\s*>$', ' />')
            }
        }

        if ($newTag -cne $rawTag) {
            [void]$replacements.Add([PSCustomObject]@{
                Start = $tag.Start
                Length = $tag.End - $tag.Start
                Text = $newTag
            })
        }
    }
    $updatedCount = $matchedIds.Count
    $newLines = New-Object 'System.Collections.Generic.List[string]'
    foreach ($entry in $incoming.GetEnumerator()) {
        if (-not $existingIds.Contains($entry.Key)) {
            $newMapping = '    <i3dMapping id="' + (Escape-XmlAttribute -Value $entry.Key) + '" node="' + (Escape-XmlAttribute -Value $entry.Value) + '" />'
            [void]$newLines.Add($newMapping)
            [void]$existingIds.Add($entry.Key)
        }
    }
    $addedCount = $newLines.Count

    $sectionLineStart = Get-LineStart -Text $xmlText -Position $section.Start
    $sectionPrefix = $xmlText.Substring($sectionLineStart, $section.Start - $sectionLineStart)
    $sectionIndent = ''
    if ($sectionPrefix -match '^[\t ]*$') {
        $sectionIndent = $sectionPrefix
    }

    $childIndent = $sectionIndent + '    '
    foreach ($tag in $existingTags) {
        $tagLineStart = Get-LineStart -Text $xmlText -Position $tag.Start
        $tagPrefix = $xmlText.Substring($tagLineStart, $tag.Start - $tagLineStart)
        if ($tagPrefix -match '^[\t ]*$') {
            $childIndent = $tagPrefix
            break
        }
    }
    $newLinesIndented = New-Object 'System.Collections.Generic.List[string]'
    foreach ($line in $newLines) {
        [void]$newLinesIndented.Add($childIndent + $line.TrimStart())
    }

    if ($addedCount -gt 0 -and $section.SelfClosing) {
        $rawSection = $xmlText.Substring($section.Start, $section.End - $section.Start)
        $beforeEnd = $rawSection.Substring(0, $rawSection.Length - 1).TrimEnd()
        $slash = $beforeEnd.LastIndexOf('/')
        if ($slash -lt 0) {
            throw (Get-LocalizedText -German 'Die leere i3dMappings-Sektion konnte nicht erweitert werden.' -English 'The empty i3dMappings section could not be expanded.')
        }
        $openSection = $beforeEnd.Substring(0, $slash).TrimEnd() + '>'
        if ($sectionPrefix -match '^[\t ]*$') {
            $replacementText = $openSection + $newline + ($newLinesIndented -join $newline) + $newline + $sectionIndent + '</i3dMappings>'
        } else {
            $replacementText = $openSection + ($newLinesIndented -join '') + '</i3dMappings>'
        }
        [void]$replacements.Add([PSCustomObject]@{
            Start = $section.Start
            Length = $section.End - $section.Start
            Text = $replacementText
        })
    } elseif ($addedCount -gt 0) {
        $closeLineStart = Get-LineStart -Text $xmlText -Position $section.CloseStart
        $closePrefix = $xmlText.Substring($closeLineStart, $section.CloseStart - $closeLineStart)
        if ($closePrefix -match '^[\t ]*$') {
            $insertAt = $closeLineStart
            $insertText = ($newLinesIndented -join $newline) + $newline
        } else {
            $insertAt = $section.CloseStart
            $insertText = $newline + ($newLinesIndented -join $newline) + $newline + $sectionIndent
        }
        [void]$replacements.Add([PSCustomObject]@{
            Start = $insertAt
            Length = 0
            Text = $insertText
        })
    }

    $updatedText = $xmlText
    foreach ($replacement in ($replacements | Sort-Object -Property Start -Descending)) {
        $updatedText = $updatedText.Remove($replacement.Start, $replacement.Length).Insert($replacement.Start, $replacement.Text)
    }

    if ($replacements.Count -gt 0) {
        $updatedPayload = $encoding.GetBytes($updatedText)
        $finalBytes = New-Object byte[] ($bomLength + $updatedPayload.Length)
        if ($bomLength -gt 0) {
            [System.Array]::Copy($sourceBytes, 0, $finalBytes, 0, $bomLength)
        }
        [System.Array]::Copy($updatedPayload, 0, $finalBytes, $bomLength, $updatedPayload.Length)

        $directory = [System.IO.Path]::GetDirectoryName($resolvedTarget)
        $temporaryFile = [System.IO.Path]::Combine(
            $directory,
            ([System.IO.Path]::GetRandomFileName() + '.i3dMappingExporter.tmp')
        )
        try {
            [System.IO.File]::WriteAllBytes($temporaryFile, $finalBytes)
            try {
                [System.IO.File]::Replace($temporaryFile, $resolvedTarget, $null)
            } catch {
                $backupFile = $temporaryFile + '.bak'

                [System.IO.File]::Move($resolvedTarget, $backupFile)
                try {
                    [System.IO.File]::Move($temporaryFile, $resolvedTarget)
                    [System.IO.File]::Delete($backupFile)
                } catch {
                    if (-not [System.IO.File]::Exists($resolvedTarget) -and [System.IO.File]::Exists($backupFile)) {
                        [System.IO.File]::Move($backupFile, $resolvedTarget)
                    }
                    throw
                }
            }
        } finally {
            if ([System.IO.File]::Exists($temporaryFile)) {
                [System.IO.File]::Delete($temporaryFile)
            }
        }
    }

    $successMessage = Get-LocalizedText -German 'XML aktualisiert: {0} Mapping(s) aktualisiert, {1} hinzugefuegt.' -English 'XML updated: {0} mapping(s) updated, {1} added.'
    Show-Result -Message ($successMessage -f $updatedCount, $addedCount)
} catch {
    $errorTitle = Get-LocalizedText -German 'XML wurde nicht aktualisiert:' -English 'XML was not updated:'
    Show-Result -Message ($errorTitle + [string][char]13 + [char]10 + $_.Exception.Message) -IsError $true
    exit 1
}